### ISSUE TITLE
Help:binding-python does not exist in some static methods of c++

### ISSUE THREAD

**Issue by AbelChan1989** [mosra/magnum-bindings#7]
class Path:Magnum::GL::AbstractFramebuffer class

static void blit(AbstractFramebuffer& source,
AbstractFramebuffer& destination,
const Range2Di& sourceRectangle,
const Range2Di& destinationRectangle,
FramebufferBlitMask mask,
FramebufferBlitFilter filter)
Copy block of pixels.

static void blit(AbstractFramebuffer& source,
AbstractFramebuffer& destination,
const Range2Di& rectangle,
FramebufferBlitMask mask)

**Comment by mosra** [comment]
Hi! Sorry for the late reaction.

Implemented in 016f5954e3815e098d4ed9897de13eb424860b45, [docs here](https://doc.magnum.graphics/python/magnum/gl/Framebuffer/#blit-6b1e1).
